# Generated by Django 5.0.3 on 2024-07-22 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_of_class', models.CharField(max_length=150)),
                ('type_of_class', models.CharField(max_length=50, null=True)),
                ('date_class', models.DateField(null=True)),
                ('identifier', models.CharField(max_length=10, null=True, unique=True)),
                ('teacher_for_change', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'лекція',
                'verbose_name_plural': 'лекції',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='CollageGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'група коледжу',
                'verbose_name_plural': 'групи коледжу',
                'db_table': 'collage_groups',
            },
        ),
        migrations.CreateModel(
            name='ExcelFileChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=70)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=150)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='item_journals.collagegroups')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенти',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=70)),
                ('groups', models.ManyToManyField(related_name='subjects', to='item_journals.collagegroups', verbose_name='групи')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предмети',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='StudentsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=5, null=True)),
                ('date_of_progress', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_edit_progress', models.DateTimeField(auto_now=True, null=True)),
                ('mark_element_id', models.CharField(max_length=50, null=True)),
                ('lesson_date', models.DateField(null=True)),
                ('is_valuable', models.BooleanField(default=True)),
                ('multi_mark_value', models.CharField(blank=True, default='11', max_length=2)),
                ('class_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.classmodel')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.subject')),
            ],
            options={
                'verbose_name': 'успішність студентів',
                'verbose_name_plural': 'успішність студентів',
                'db_table': 'progress',
            },
        ),
        migrations.AddField(
            model_name='classmodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_full_name', models.CharField(max_length=150)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'викладач',
                'verbose_name_plural': 'викладачі',
                'db_table': 'teachers',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='item_journals.teacher', verbose_name='викладачі'),
        ),
        migrations.CreateModel(
            name='WorkedOutLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_reason', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_worked_out', models.BooleanField(default=False)),
                ('worked_on', models.IntegerField(blank=True, null=True)),
                ('before_worked_out', models.CharField(blank=True, max_length=2, null=True)),
                ('date_worked_out', models.DateField(null=True)),
                ('mark_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.studentsprogress')),
            ],
            options={
                'verbose_name': 'відпрацювання',
                'verbose_name_plural': 'відпрацювання',
                'db_table': 'worked_out',
            },
        ),
    ]
