# Generated by Django 5.0.3 on 2024-07-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacherGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_journals.collagegroups')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_journals.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_journals.teacher')),
            ],
            options={
                'verbose_name': 'викладач для групи предмета',
                'verbose_name_plural': 'викладачі для груп предметів',
                'db_table': 'subject_teacher_group',
                'unique_together': {('subject', 'teacher', 'group')},
            },
        ),
    ]
