# Generated by Django 5.0.3 on 2024-07-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0002_subjectteachergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
    ]
