# Generated by Django 5.0.3 on 2024-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0003_remove_subject_groups_remove_subject_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(related_name='subjects', to='item_journals.collagegroups', verbose_name='групи'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='item_journals.teacher', verbose_name='викладачі'),
        ),
    ]
