# Generated by Django 5.0.3 on 2024-07-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0004_subject_groups_subject_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='subject_teacher_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.subjectteachergroup'),
        ),
        migrations.AddField(
            model_name='subjectteachergroup',
            name='theme',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
