# Generated by Django 5.0.3 on 2024-07-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0006_remove_classmodel_subject_teacher_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.collagegroups'),
        ),
    ]
