# Generated by Django 5.0.3 on 2024-07-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0007_classmodel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='group',
        ),
    ]
