# Generated by Django 5.0.3 on 2024-07-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0008_remove_classmodel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='subject_teacher_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.subjectteachergroup'),
        ),
    ]
