# Generated by Django 5.0.3 on 2024-07-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0012_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='collagegroups',
            name='curator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_group', to='item_journals.curator'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curator_relation', to='item_journals.collagegroups'),
        ),
    ]
