# Generated by Django 5.0.3 on 2024-07-23 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0013_collagegroups_curator_alter_curator_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collagegroups',
            name='curator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_group', to='item_journals.curator', verbose_name='Куратор групи'),
        ),
        migrations.AlterField(
            model_name='collagegroups',
            name='group_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва групи'),
        ),
        migrations.AlterField(
            model_name='subjectteachergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_journals.collagegroups', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='subjectteachergroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_journals.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectteachergroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_journals.teacher', verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_full_name',
            field=models.CharField(max_length=150, verbose_name="Повне ім'я викладача"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='workedoutlogs',
            name='absent_reason',
            field=models.CharField(blank=True, max_length=50, verbose_name='Причина відсутності'),
        ),
        migrations.AlterField(
            model_name='workedoutlogs',
            name='before_worked_out',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Перед відпрацюванням'),
        ),
        migrations.AlterField(
            model_name='workedoutlogs',
            name='date_worked_out',
            field=models.DateField(null=True, verbose_name='Дата відпрацювання'),
        ),
        migrations.AlterField(
            model_name='workedoutlogs',
            name='worked_on',
            field=models.IntegerField(blank=True, null=True, verbose_name='Відпрацьовано на'),
        ),
    ]
