# Generated by Django 5.0.3 on 2024-07-23 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0014_alter_collagegroups_curator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='date_class',
            field=models.DateField(null=True, verbose_name='Дата заняття'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='teacher_for_change',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Викладач на заміну'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='theme_of_class',
            field=models.CharField(max_length=150, verbose_name='Тема заняття'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='type_of_class',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип заняття'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curator_relation', to='item_journals.collagegroups', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='item_journals.collagegroups', verbose_name='Група студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_full_name',
            field=models.CharField(max_length=150, verbose_name="Повне ім'я студента"),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='studentsprogress',
            name='mark',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Оцінка'),
        ),
        migrations.AlterField(
            model_name='studentsprogress',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='item_name',
            field=models.CharField(max_length=70, verbose_name='Назва предмету'),
        ),
    ]
