# Generated by Django 4.2.14 on 2024-07-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0014_subgroup_student_subgroup_subject_subgroups'),
        ('item_journals', '0015_alter_classmodel_date_class_and_more'),
    ]

    operations = [
    ]
