# Generated by Django 4.2.14 on 2024-07-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0017_alter_student_group_alter_student_student_full_name_and_more'),
        ('item_journals', '0017_remove_curator_group_alter_student_group_and_more'),
    ]

    operations = [
    ]
