# Generated by Django 4.2.14 on 2024-07-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0019_curator_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='group',
            field=models.OneToOneField(blank=True, default=7, on_delete=django.db.models.deletion.CASCADE, related_name='curator_relation', to='item_journals.collagegroups', verbose_name='Група'),
            preserve_default=False,
        ),
    ]
