# Generated by Django 4.2.14 on 2024-07-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0022_alter_curator_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collagegroups',
            name='curator',
        ),
    ]
