# Generated by Django 4.2.14 on 2024-07-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0023_remove_collagegroups_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_journals.subgroup'),
        ),
    ]
