# Generated by Django 4.2.14 on 2024-07-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0024_classmodel_sub_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subgroup',
            unique_together={('name', 'parent_group')},
        ),
    ]
