# Generated by Django 4.2.14 on 2024-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0026_studentsprogress_subgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeForLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'тема для заняття',
                'verbose_name_plural': 'теми для заняття',
                'db_table': 'themes',
            },
        ),
        migrations.CreateModel(
            name='TypeForLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'тип для заняття',
                'verbose_name_plural': 'типи для заняття',
                'db_table': 'types',
            },
        ),
    ]
