# Generated by Django 4.2.14 on 2024-07-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0027_themeforlesson_typeforlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeforlesson',
            name='for_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_journals.typeforlesson'),
        ),
        migrations.AddField(
            model_name='themeforlesson',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_journals.subject'),
        ),
    ]
