# Generated by Django 4.2.14 on 2024-08-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0017_classmodel_subgroup_alter_student_group_and_more'),
        ('item_journals', '0028_themeforlesson_for_type_themeforlesson_item'),
    ]

    operations = [
    ]
