# Generated by Django 4.2.14 on 2024-08-02 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0029_merge_20240802_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='subgroup',
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='item_journals.collagegroups', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_full_name',
            field=models.CharField(max_length=150, verbose_name="Повне ім'я"),
        ),
        migrations.AlterField(
            model_name='student',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='item_journals.subgroup', verbose_name='Підгрупа'),
        ),
        migrations.AlterField(
            model_name='studentsprogress',
            name='class_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.classmodel', verbose_name='Лекція'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Назва підгрупи'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='item_journals.collagegroups', verbose_name='Батьківська група'),
        ),
        migrations.AlterField(
            model_name='themeforlesson',
            name='for_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_journals.typeforlesson', verbose_name='Для типу'),
        ),
        migrations.AlterField(
            model_name='themeforlesson',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_journals.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='themeforlesson',
            name='theme_name',
            field=models.CharField(max_length=100, verbose_name='Назва теми'),
        ),
        migrations.AlterField(
            model_name='typeforlesson',
            name='type_name',
            field=models.CharField(max_length=50, verbose_name='Назва типу'),
        ),
    ]
