# Generated by Django 4.2.14 on 2024-08-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0031_alter_classmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_journals.collagegroups', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_journals.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='item_name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Назва предмету'),
        ),
        migrations.AlterField(
            model_name='typeforlesson',
            name='type_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва типу'),
        ),
        migrations.AlterUniqueTogether(
            name='themeforlesson',
            unique_together={('theme_name', 'item', 'for_type')},
        ),
    ]
