# Generated by Django 4.2.14 on 2024-08-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0032_alter_classmodel_group_alter_classmodel_subject_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectteachergroup',
            unique_together={('subject', 'group')},
        ),
    ]
