# Generated by Django 4.2.14 on 2024-08-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0033_alter_subjectteachergroup_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subgroups',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
    ]
