# Generated by Django 4.2.14 on 2024-08-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0035_remove_subject_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс студента'),
        ),
    ]
