# Generated by Django 4.2.14 on 2024-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0036_student_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='item_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Назва предмету'),
        ),
    ]
