# Generated by Django 4.2.14 on 2024-09-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0037_alter_subject_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subgroups',
            field=models.ManyToManyField(blank=True, null=True, to='item_journals.subgroup', verbose_name='Підгрупи'),
        ),
    ]
