# Generated by Django 4.2.14 on 2024-09-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0041_alter_student_subgroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subgroup',
        ),
    ]
