# Generated by Django 4.2.14 on 2024-09-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_journals', '0042_remove_student_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteachergroup',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='grps', to='item_journals.collagegroups', verbose_name='Групи'),
        ),
    ]
